### ISSUE TITLE
Generate Traffic Light emulator function.

### ISSUE THREAD

**Issue by peterbarry** [CarND-Capstone-Defender/car-nd-capstone#4]
Create a component to generate /traffic_waypoint emulated data. Can be simple user keyboard control to indicate a traffic light at fixed point ahead, and another key to clear. 

This will allow clean forward progress on two parts of the project at the same time.

**Comment by AntoniaSophia** [comment]
Implementation of a command line injector for Traffic Light occurence. It will be a separate ROS node called TLInjector (located in file tl_injector.py).

NOTE: I've not used the original topic /traffic_waypoint but created a new one called /traffic_waypoint_injection --> contains the closest waypoint as well as the color of the traffic light


How to run the TL injector ?
- use the Docker environment
- attach a new console to a running Docker instance
- run the injector as separate ROS node
- type 'r' or 'y' or 'g' (or 'x' to stop the injector)
- subscribe to topic /traffic_waypoint_injection

Example:
./attachToContainer.sh 
./runTL_injector.sh
r

type 'r' in order to inject a red traffic light
type 'y' in order to inject a yellow traffic light
type 'g' in order to inject a green traffic light
type 'x' in order to stop the TL injector
